version: "2"
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: mjenz/rpi-openvpn
    container_name: openvpn
      #ports:
      #- 1194:1194/udp
      #- 943:943/tcp
    network_mode: "host"
    restart: always
    volumes:
      - /home/pi/Volumes/ovpn_data_raspi/:/etc/openvpn
